TABLE 		= TABLE_C_S6A_LR_B_S6JTEX

CYCLE_DEBUT	= 42
CYCLE_FIN	= 79
TRACE_DEBUT	= 1
TRACE_FIN	= 254

ORF		= C_S6A_LR_ORF.dat
VERBOSE		= 2

ID_LAT		= LATITUDE
ID_LON		= LONGITUDE

#################################

ALGO      	= ABAQUE_2D
ID_CHAMP  	= SSB_TEMP_1
PARAM_ALGO	= /home/hlafargue/ssb_fortran/Table_maj_BEM_S6_LR_SSB_TMP1.par | B | 1 | 1 | SSB_CORRECTION_PRINCIPAL_COMPONENT_2 | SSB_CORRECTION_PRINCIPAL_COMPONENT_1

